************* Module transform_pdf
pdf_report/transform_pdf.py:292:4: E1120: No value for argument 'report_filename' in function call (no-value-for-parameter)

-----------------------------------
Your code has been rated at 9.33/10

************* Module pdf_report
pdf_report/pdf_report.py:1:0: C0114: Missing module docstring (missing-module-docstring)
pdf_report/pdf_report.py:26:11: W0718: Catching too general exception Exception (broad-exception-caught)

-----------------------------------
Your code has been rated at 8.95/10

************* Module extract_pdf
pdf_report/extract_pdf.py:38:4: W0702: No exception type(s) specified (bare-except)
pdf_report/extract_pdf.py:30:0: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)

-----------------------------------
Your code has been rated at 9.17/10

************* Module load_pdf
pdf_report/load_pdf.py:44:11: W0718: Catching too general exception Exception (broad-exception-caught)
pdf_report/load_pdf.py:143:4: E1120: No value for argument 'report_filename' in function call (no-value-for-parameter)
pdf_report/load_pdf.py:13:0: W0611: Unused connect imported from psycopg2 (unused-import)
pdf_report/load_pdf.py:14:0: W0611: Unused cursor imported from psycopg2.extensions (unused-import)
pdf_report/load_pdf.py:15:0: W0611: Unused RealDictCursor imported from psycopg2.extras (unused-import)

-----------------------------------
Your code has been rated at 8.83/10


------------------------------------
Your code has been rated at 10.00/10


------------------------------------
Your code has been rated at 10.00/10

************* Module db_connection
archive/db_connection.py:44:15: W0718: Catching too general exception Exception (broad-exception-caught)
archive/db_connection.py:52:15: W0718: Catching too general exception Exception (broad-exception-caught)
archive/db_connection.py:52:8: W0612: Unused variable 'e' (unused-variable)

-----------------------------------
Your code has been rated at 8.89/10


------------------------------------
Your code has been rated at 10.00/10


------------------------------------
Your code has been rated at 10.00/10

************* Module sns_reporting
national_rail/sns_reporting.py:93:11: W0718: Catching too general exception Exception (broad-exception-caught)
national_rail/sns_reporting.py:97:0: R0913: Too many arguments (6/5) (too-many-arguments)
national_rail/sns_reporting.py:125:0: R0914: Too many local variables (19/15) (too-many-locals)
national_rail/sns_reporting.py:180:11: W0718: Catching too general exception Exception (broad-exception-caught)

-----------------------------------
Your code has been rated at 9.62/10

************* Module load_national
national_rail/load_national.py:58:11: W0718: Catching too general exception Exception (broad-exception-caught)
national_rail/load_national.py:105:11: W0718: Catching too general exception Exception (broad-exception-caught)

-----------------------------------
Your code has been rated at 9.63/10

************* Module national_rail
national_rail/national_rail.py:42:11: W0718: Catching too general exception Exception (broad-exception-caught)

-----------------------------------
Your code has been rated at 9.60/10

************* Module extract_national
national_rail/extract_national.py:8:0: W0611: Unused load_dotenv imported from dotenv (unused-import)

-----------------------------------
Your code has been rated at 9.62/10


------------------------------------
Your code has been rated at 10.00/10


------------------------------------
Your code has been rated at 10.00/10

************* Module realtime_trains
realtime_trains/realtime_trains.py:36:11: W0718: Catching too general exception Exception (broad-exception-caught)

-----------------------------------
Your code has been rated at 9.52/10

************* Module load_real
realtime_trains/load_real.py:53:0: R0914: Too many local variables (24/15) (too-many-locals)
realtime_trains/load_real.py:136:11: W0718: Catching too general exception Exception (broad-exception-caught)
realtime_trains/load_real.py:240:0: R0913: Too many arguments (6/5) (too-many-arguments)
realtime_trains/load_real.py:265:15: W0718: Catching too general exception Exception (broad-exception-caught)

-----------------------------------
Your code has been rated at 9.67/10


------------------------------------
Your code has been rated at 10.00/10


------------------------------------
Your code has been rated at 10.00/10


------------------------------------
Your code has been rated at 10.00/10

